services:
  local-server:
    build: .
    container_name: ave-local-server
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: python launcher.py
    volumes:
      - ./assets/userdata:/app/assets/userdata
      - ./userconfig.txt:/app/userconfig.txt
    environment:
      - DISPLAY=:99
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - MODULE=local-server
    networks:
      - ave-net

  promocode:
    build: .
    container_name: ave-promocode
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: python launcher.py
    volumes:
      - ./assets/userdata:/app/assets/userdata
      - ./userconfig.txt:/app/userconfig.txt
    environment:
      - DISPLAY=:99
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - MODULE=promocode
      - DOCKER_SOCKET_HOST=local-server
    networks:
      - ave-net

  rain:
    build: .
    container_name: ave-rain
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: python launcher.py
    volumes:
      - ./assets/userdata:/app/assets/userdata
      - ./userconfig.txt:/app/userconfig.txt
    environment:
      - DISPLAY=:99
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - MODULE=rain
      - DOCKER_SOCKET_HOST=local-server
    networks:
      - ave-net

networks:
  ave-net:
    driver: bridge
