#!/bin/bash
echo "=== Ave X Launcher - Droplet ==="
echo ""
echo "Arrancar todo:"
echo "  docker compose up -d"
echo ""
echo "Ver logs:"
echo "  docker compose logs -f"
echo ""
echo "Parar todo:"
echo "  docker compose down"
echo ""
echo "Arrancar individual:"
echo "  docker compose run --rm local-server"
echo "  docker compose run --rm promocode"
echo "  docker compose run --rm rain"
